# Generated by Django 3.0.7 on 2020-09-01 14:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_date', models.DateField(blank=True)),
                ('contest_started', models.BooleanField(default=False)),
                ('contest_completed', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='team_name')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team_a', models.IntegerField(default=0)),
                ('score_team_b', models.IntegerField(default=0)),
                ('game_is_played', models.BooleanField(default=False)),
                ('game_result', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('game_time', models.TimeField(default=datetime.time(14, 33, 34, 766463))),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sergtoto.Contest')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_a', to='sergtoto.Team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_b', to='sergtoto.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game_result', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sergtoto.Contest')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sergtoto.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
