# Generated by Django 3.0.7 on 2020-10-05 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='valid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 58, 34, 815576, tzinfo=utc)),
        ),
    ]
