# Generated by Django 3.0.7 on 2020-10-04 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_loose',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_won',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 15, 1, 49, 248977, tzinfo=utc)),
        ),
    ]
