# Generated by Django 3.0.7 on 2020-09-01 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='contest',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.TimeField(default=datetime.time(14, 53, 1, 174163)),
        ),
    ]
