# Generated by Django 3.0.7 on 2020-10-05 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0002_auto_20201004_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='selected_for_competition',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 16, 52, 24, 674306, tzinfo=utc)),
        ),
    ]
