# Generated by Django 3.0.7 on 2020-09-13 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0002_auto_20200901_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='game_result',
        ),
        migrations.AddField(
            model_name='bet',
            name='draw',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='team_a_win',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='team_b_win',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='game_is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.TimeField(default=datetime.time(8, 27, 20, 628104)),
        ),
    ]
