# Generated by Django 3.0.7 on 2020-09-20 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0002_auto_20200915_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date_time',
            field=models.DateTimeField(default=datetime.time(14, 26, 20, 48539)),
        ),
    ]
