# Generated by Django 3.0.7 on 2020-10-05 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0002_auto_20201005_2358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='ParticipantTeam',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 24, 10, 476239, tzinfo=utc)),
        ),
    ]
