# Generated by Django 3.0.7 on 2020-10-05 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0003_auto_20201005_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='selected_for_competition',
            new_name='selected_for_contest',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 17, 11, 12, 284870, tzinfo=utc)),
        ),
    ]
