# Generated by Django 3.0.7 on 2020-09-20 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0003_auto_20200920_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='contest_date',
            new_name='contest_start_date',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date_time',
            field=models.DateTimeField(default=datetime.time(14, 29, 3, 649003)),
        ),
    ]
