# Generated by Django 3.0.7 on 2020-09-15 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0003_auto_20200913_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='game_length',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.TimeField(default=datetime.time(6, 43, 54, 842465)),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_a', to='sergtoto.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_b', to='sergtoto.Team'),
        ),
    ]
