# Generated by Django 3.0.7 on 2020-09-15 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0004_auto_20200915_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.TimeField(default=datetime.time(7, 1, 54, 372234)),
        ),
    ]
