# Generated by Django 3.0.7 on 2020-10-05 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0004_auto_20201005_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='max_teams',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 18, 21, 7, 587637, tzinfo=utc)),
        ),
    ]
