# Generated by Django 3.0.7 on 2020-09-15 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0005_auto_20200915_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='pauza_length',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='contest',
            name='game_length',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.TimeField(default=datetime.time(7, 10, 37, 662879)),
        ),
    ]
