# Generated by Django 3.0.7 on 2020-10-05 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sergtoto', '0005_auto_20201005_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 18, 32, 30, 517120, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sergtoto.Contest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sergtoto.Team')),
            ],
        ),
    ]
